language: python
sudo: false
python:
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -Ur requirements-dev.txt
  - python setup.py develop

script:
  # asyncio git repo has only *.pyx files, so install cython too.
  - '[ -z "$LATEST_ASYNCIO" ] || pip install -U cython git+https://github.com/KeepSafe/aiohttp.git'
  - python setup.py test

env:
  matrix:
    # PYTHONASYNCIODEBUG environment variable is considered as enabled if it
    # is any non empty string.
    - PYTHONASYNCIODEBUG=X LATEST_ASYNCIO=
    - PYTHONASYNCIODEBUG=  LATEST_ASYNCIO=X
