language: python
sudo: false
python:
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -Ur requirements-dev.txt
  - python setup.py develop

script:
  python setup.py test

env:
  matrix:
    # PYTHONASYNCIODEBUG environment variable is considered as enabled if it
    # is any non empty string.
    - PYTHONASYNCIODEBUG=X
    - PYTHONASYNCIODEBUG=
