language: python
sudo: false
python:
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -Ur requirements-dev.txt
  - python setup.py develop
  # aiohttp git repo has only *.pyx files, so install cython too.
  - '[ -z "$MASTER_AIOHTTP" ] || pip install -U cython git+https://github.com/KeepSafe/aiohttp.git'
  # Test on oldest supported aiohttp version.
  - '[ -z "$OLDEST_AIOHTTP" ] || pip install aiohttp==0.21.4'

script:
  - python setup.py test

env:
  matrix:
    # PYTHONASYNCIODEBUG environment variable is considered as enabled if it
    # is any non empty string.
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=  OLDEST_AIOHTTP=
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=  OLDEST_AIOHTTP=
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=x OLDEST_AIOHTTP=
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=x OLDEST_AIOHTTP=
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=  OLDEST_AIOHTTP=x
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=  OLDEST_AIOHTTP=x
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=x OLDEST_AIOHTTP=x
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=x OLDEST_AIOHTTP=x
