language: python
sudo: false
python:
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -Ur requirements-dev.txt
  - python setup.py develop
  # aiohttp git repo has only *.pyx files, so install cython too.
  - '[ -z "$MASTER_AIOHTTP" ] || pip install -U cython git+https://github.com/KeepSafe/aiohttp.git'
  - '[ -z "$AIOHTTP_0_20_2" ] || pip install aiohttp==0.20.2'

script:
  - python setup.py test

env:
  matrix:
    # PYTHONASYNCIODEBUG environment variable is considered as enabled if it
    # is any non empty string.
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=  AIOHTTP_0_20_2=
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=  AIOHTTP_0_20_2=
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=x AIOHTTP_0_20_2=
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=x AIOHTTP_0_20_2=
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=  AIOHTTP_0_20_2=x
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=  AIOHTTP_0_20_2=x
    - PYTHONASYNCIODEBUG=  MASTER_AIOHTTP=x AIOHTTP_0_20_2=x
    - PYTHONASYNCIODEBUG=x MASTER_AIOHTTP=x AIOHTTP_0_20_2=x
